version: '3.8'

services:
  cockroach:
    image: cockroachdb/cockroach:v25.2.1
    container_name: crdb-single-node
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - crdb-data:/cockroach/cockroach-data

  cockroachdb-mcp-server:
    build:
      context: .
    container_name: cockroachdb-mcp-server
    ports:
      - "8081:8080"
    environment:
      - CRDB_URL=postgresql://root@host.docker.internal:26257/defaultdb?sslmode=disable

volumes:
  crdb-data:
    name: crdb-data
