site_name: CockroachDB MCP Server
repo_url: https://github.com/viragtripathi/cockroachdb-mcp-server
repo_name: cockroachdb-mcp-server
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate

nav:
  - Overview: index.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
