name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Start CockroachDB (latest)
        run: |
          docker run -d \
            --name crdb \
            -p 26257:26257 \
            -p 8080:8080 \
            cockroachdb/cockroach:latest \
            start-single-node --insecure

      - name: Set CRDB_URL environment variable
        run: echo "CRDB_URL=cockroachdb://root@localhost:26257/defaultdb?sslmode=disable" >> $GITHUB_ENV

      - name: Lint with ruff (non-blocking)
        run: ruff check . || true

      - name: Format check with black
        run: black --check cockroachdb_mcp_server

      - name: Run tests
        run: PYTHONPATH=. pytest tests/
        env:
          CRDB_URL: postgresql://root@localhost:26257/defaultdb?sslmode=disable
          MCP_DEMO_MODE: "true"
